apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multifeature-app
  name: multifeature-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multifeature-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: multifeature-app
    spec:
      containers:
      - image: romeolandry/vuejs-multifeature:latest
        imagePullPolicy: Always
        name: vuejs-multifeature
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multifeature-app
  name: multifeature-app
  namespace: default
spec:
  ports:
  - nodePort: 30819
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: multifeature-app
  sessionAffinity: None
  type: LoadBalancer
